delete from enfermedades;
delete from usuario_seguir_usuario;
delete from usuarios;
delete from rutina_actividad;
delete from actividades;
delete from maquinas;
delete from reservas;
delete from rutinas;
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(1,true,'Benziane','adelbenziane@gmail.com',true,'1999-05-02','Adel','adelfr',0,0);
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(2,true,'admin','admin@gmail.com',true,'1998-12-13','admin','admin',0,0);
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(3,true,'gomez','juangomez@gmail.com',true,'2000-12-12','juan','juan2000',0,2);
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(4,true,'ramirez','pedroramirez@gmail.com',true,'2001-12-12','pedro','pedro2000',0,2);
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(5,true,'ruiz','ivanruiz@hotmail.com',true,'2000-04-12','ivan','ivan2000',0,2);
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(6,true,'gonzalez','marcgonzalez@gmail.com',true,'2000-06-10','marc','marc2000',0,2);
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(7,true,'lopez','mariolopez@gmail.com',true,'2000-12-20','mario','mario2000',0,2);
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(8,true,'esponisa','javierespinosa@gmail.com',true,'2000-05-11','Javier','javier2000',0,1);
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(9,true,'valera','luisvalera@gmail.com',true,'2000-05-13','Luis','luis2000',5,1);
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(10,true,'garcia','miguelgarcia@gmail.com',true,'2000-08-31','Miguel','miguel2000',6,1);
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(11,true,'sanchez','antoniosanchez@gmail.com',true,'2001-05-25','Antonio','antonio2000',5,1);
insert into usuarios(id,acceso,apellidos,email,enabled,fecha_nacimiento,nombre,password,puntos,tipo_user) values(12,true,'jimenez','marcosjimenez@gmail.com',true,'2002-04-01','Marcos','marcos2000',3,1);
insert into maquinas(id,imagen,nombre,fecha_registro) values(1,'ejercicio_pecho.jpg','Ejercicio Pecho','2023-02-28');
insert into maquinas(id,imagen,nombre,fecha_registro) values(2,'ejercicio_pecho1.jpg','Ejercicio pecho con mancuernas','2023-02-28');
insert into maquinas(id,imagen,nombre,fecha_registro) values(3,'ejercicio_pecho2.gif','Ejercicio pecho central','2023-02-28');
insert into maquinas(id,imagen,nombre,fecha_registro) values(4,'ejercicio_espalda2.jpg','Ejercicio espalda barra para dorsal ','2023-02-28');
insert into maquinas(id,imagen,nombre,fecha_registro) values(5,'ejercicio_espalda1.jpg','Ejercicio espalda para dorsal','2023-02-28');
insert into maquinas(id,imagen,nombre,fecha_registro) values(6,'ejercicio_espalda3.jpg','Ejercicio espalda entera','2023-02-28');
insert into maquinas(id,imagen,nombre,fecha_registro) values(7,'ejercicio_espalda4.jpg','Ejercicio espalda columna','2023-02-28');
insert into maquinas(id,imagen,nombre,fecha_registro) values(8,'ejercicio_espalda5.jpg','Ejercicio dorsal y triceps','2023-02-28');
insert into maquinas(id,imagen,nombre,fecha_registro) values(9,'ejercicio_trapecio.jpg','Ejercicio trapecio','2023-02-28');
insert into maquinas(id,imagen,nombre,fecha_registro) values(10,'ejercicio_biceps.jpg','Ejercicio biceps barra','2023-02-28');
insert into maquinas(id,imagen,nombre,fecha_registro) values(11,'ejercicio_biceps1.jpg','Ejercicio biceps mancuernas','2023-02-28');
insert into maquinas(id,imagen,nombre,fecha_registro) values(12,'ejercicio_gemelos.jpg','Ejercicio para gemelos','2023-02-28');
insert into actividades(id,nombre,repeticiones,series,zona_cuerpo,maquina_id,puntos) values(1,'ejercicio del pecho superior',10,4,0,1,2);